package-lock.json, packages/spacecat-shared-data-access/src/models/audit.js
This PR adds the broken-backlinks as supported audit type for [SITES-18417](https://jira.corp.adobe.com/browse/SITES-18417).
Relates to https://github.com/adobe/spacecat-audit-worker/pull/77, https://github.com/adobe/spacecat-audit-post-processor/pull/37, https://github.com/adobe/spacecat-audit-scheduler/pull/27, https://github.com/adobe/spacecat-api-service/pull/97
=> feat: add broken-backlinks audit type (SITES-18417)

package-lock.json, packages/spacecat-shared-data-access/src/models/audit.js
FIx for: not all audits have as result scores and adding an audit without scores is failing, hence initializing the scores to an empty object, if no scores in the result.
=> fix: initialize scores as an empty object

packages/spacecat-shared-data-access/test/unit/models/base.test.js
In some cases, the test failed with assertion error, because it compared expected with passed `createdAt` on a new record (no id), whereas for new records a createdAt is generated in the constructor.
```
AssertionError: expected '2024-01-18T16:23:59.276Z' to equal '2024-01-18T16:23:59.275Z'
```
=> fix: createdAt test

packages/spacecat-shared-data-access/src/models/audit.js, packages/spacecat-shared-data-access/test/unit/models/audit.test.js
Fix and test for https://github.com/adobe/spacecat-shared/pull/87
=> fix: audit result scores init, test

packages/spacecat-shared-data-access/src/models/organization.js, packages/spacecat-shared-data-access/src/models/site.js, packages/spacecat-shared-data-access/test/unit/models/site.test.js
We have to fix a default organization as the all-sites-with-org index expects its partition key (the site's org id) to be set. this prevents errors like these:
```
One or more parameter values were invalid: Type mismatch for Index Key organizationId Expected: S Actual: NULL IndexName: all-sites-organizations-dev
```
currently add / update sites operations are failing
=> fix: set default organization

package-lock.json, package.json
Add custom-built semantic-release-monorepo (PR opened here https://github.com/pmowrer/semantic-release-monorepo/pull/148) to support ESM.
Using custom build published from here for the time being: https://github.com/solaris007/semantic-release-monorepo/tree/fix-esm-module
=> fix: semantic-release-monorepo ESM

packages/spacecat-shared-data-access/src/models/site/audit-config.js, packages/spacecat-shared-data-access/test/unit/models/site.test.js, packages/spacecat-shared-data-access/test/unit/models/site/audit-config.test.js
SEO-related audit types should have default value for disabled true (we enable one by one the sites, so we don't waste Ahrefs API units on sites not of interest at this post.
=> feat: default value for disabled property of audit config

packages/spacecat-shared-data-access/test/unit/models/base.test.js
In some cases, the test failed with assertion error, because it compared expected with passed `updatedAt` on a new record (no id), whereas for new records an `updatedAt` is generated in the constructor.
```
AssertionError: expected '2024-01-18T16:23:59.276Z' to equal '2024-01-18T16:23:59.275Z'
```
=> test: fix updatedAt test

packages/spacecat-shared-data-access/README.md, packages/spacecat-shared-data-access/docs/schema.json, packages/spacecat-shared-data-access/package.json, packages/spacecat-shared-data-access/src/dto/site-candidate.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/index.js, packages/spacecat-shared-data-access/src/models/site-candidate.js, packages/spacecat-shared-data-access/src/service/index.js, packages/spacecat-shared-data-access/src/service/site-candidates/accessPatterns.js, packages/spacecat-shared-data-access/src/service/site-candidates/index.js, packages/spacecat-shared-data-access/test/it/db.test.js, packages/spacecat-shared-data-access/test/it/generateSampleData.js, packages/spacecat-shared-data-access/test/unit/models/site-candidate.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js, packages/spacecat-shared-data-access/test/unit/service/site-candidates/index.test.js
This PR introduces the Site Candidate Data Model to manage the site discovery flow. The primary objective is to maintain a comprehensive list of new sites and their respective statuses for potential inclusion in the Star Catalogue. The information is stored in the `site-candidates` table. The PR contains the data model itself, along with the access patterns and the functions which are used to add and modify of site candidates.
1. Upon the discovery of a new site, Spacecat will check the `site-candidates` table to ascertain whether the site has been previously discovered.
- If the site is found in the table, the candidate will be discarded.
- If the site is not found, the candidate will be added to the `site-candidates` table with the status `PENDING`
2. Subsequently, Spacecat will …
=> feat: site candidate data model

package-lock.json, packages/spacecat-shared-data-access/src/dto/organization.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/models/organization.js, packages/spacecat-shared-data-access/test/unit/models/organization.test.js
Add accessors to support the `fulfillableItems` property defined on `Organization`: https://lucid.app/lucidchart/f5480d07-626d-42e8-8eb5-39b0e9a1c75f/edit?invitationId=inv_c77bd463-5df8-4973-b70b-a8028a6ee21a&page=0_0#
Includes: 
- Model & DTO updates
- Type updates
- Test coverage
=> feat: fulfillable items support on Organization

packages/spacecat-shared-utils/src/url-helpers.js, packages/spacecat-shared-utils/test/url-helpers.test.js
two more cases added:
1. CDN configurations may contain uppercase subdomains (ie WWW)
2. x-fw-host values coming from cdn logs might contain trailing dot **and** port
=> fix: baseurl composition fixes

package-lock.json, packages/spacecat-shared-slack-client/src/clients/elevated-slack-client.js, packages/spacecat-shared-slack-client/test/clients/elevated-slack-client.test.js
Ticket: #182
Facilitate operation of the service by sorting email addresses by their domain.
=> feat: Group email addresses by domain in the Slack ops invitation messages #182

.eslintignore, .gitignore, packages/spacecat-shared-ims-client/src/clients/ims-client.js, packages/spacecat-shared-ims-client/src/utils.js, packages/spacecat-shared-ims-client/test/clients/ims-client.test.js
Ticket: #193
Proposed addition of a new method to the ImsClient, `getImsUserProfile(imsAccessToken)`.
Currently we deal directly with email addresses from the IMS group members API. However, to support the Cloud Manager use case, we need to adapt to support project collaboration channel requests via access token. This method will bridge the gap from IMS user token to a user's email address, which we can then use to send them a Slack invitation.
=> feat: Enable retrieval of a user's email address from IMS given an access token #193

package-lock.json, packages/spacecat-shared-slack-client/README.md, packages/spacecat-shared-slack-client/src/index.js, packages/spacecat-shared-slack-client/src/wrappers/elevated-client-wrapper.js, packages/spacecat-shared-slack-client/test/wrappers/elevated-client-wrapper.test.js
Related ticket #207
Adds a wrapper for exposing an ElevatedSlackClient on the context at `context.slack.elevatedClient`.
Initial use case is to enable the API service to use an Elevated client in order to invite collab channel participants, in response to requests from Cloud Manager.
=> Feat: add elevatedSlackClientWrapper

packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
`sum_traffic_merged` can be used in the `order_by` only when we also set a `date_compared`, which we won't need/use
=> fix: ahrefs api call order_by

package-lock.json, packages/spacecat-shared-gpt-client/README.md, packages/spacecat-shared-gpt-client/package.json, packages/spacecat-shared-gpt-client/src/clients/firefall-client.js, packages/spacecat-shared-gpt-client/test/clients/firefall-client.test.js
Right now the firefall client requires a manually generated, expiring access token to be provided. This was done in the prototype stage. In order to use the client with proper ims authentication, this PR switches to using the ims client.
=> feat: use ims-client for auth

packages/spacecat-shared-google-client/src/index.d.ts, packages/spacecat-shared-google-client/src/index.js, packages/spacecat-shared-google-client/test/index.test.js
Fix the getOrganicSearchData interface parameters
=> fix: getOrganicSearchData interface params

packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
When a firefall job fails, log the error details for debugging.
=> fix: more error details for firefall job

packages/spacecat-shared-http-utils/src/index.js, packages/spacecat-shared-http-utils/test/index.test.js
This PR refactors the createResponse function to ensure proper handling of response bodies based on the content-type header. It also includes code improvements to enhance readability and maintainability.
=> fix: Refactor createResponse Function to Handle Non-JSON Content-Types

packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/models/importer/import-job.js, packages/spacecat-shared-data-access/src/service/import-job/accessPatterns.js, packages/spacecat-shared-data-access/src/service/import-job/index.js, packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js, packages/spacecat-shared-data-access/src/service/import-url/index.js, packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js
[SITES-22578](https://jira.corp.adobe.com/browse/SITES-22578)
Add the following queries to import-url and import-job entities:
- updateImportUrl
- updateImportJob
=> feat: Add update queries for import-job and import-url entites

packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/index.js, packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js, packages/spacecat-shared-data-access/src/service/import-url/index.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js
[SITES-22580](https://jira.corp.adobe.com/browse/SITES-22580)
Query the import-url table for entries matching:
JobID
Status
=> feat: query for URLs for a given jobID matching status

package-lock.json, packages/spacecat-shared-data-access/src/dto/import-url.js, packages/spacecat-shared-data-access/src/models/importer/import-url.js, packages/spacecat-shared-data-access/test/unit/models/importer/import-url.test.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js
- #268 
In order to support generating the import-report.xlsx file for an import job, we need the ability to track if a URL was skipped because it was a redirect, or if it failed for another reason.
Screenshot from an example import-report included below:
To support this, I'm proposing that we add the following properties to the import-url entities, in addition to the existing status:
```
reason: the reason that the import of a URL failed (could be the redirect destination in the case of a redirect)
path: absolute path to the resource that is being imported for the given URL
file: resulting path and filename of the imported .docx file
```
An additional status REDIRECT will also be added to `ImportUrlStatus` to facilitate generation of this report.
=> fix: #268 Import URL entities need a REDIRECT status, and additional properties for reporting

packages/spacecat-shared-ahrefs-client/src/index.d.ts, packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js, packages/spacecat-shared-data-access/src/dto/site-top-page.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/models/site-top-page.js, packages/spacecat-shared-data-access/test/it/db.test.js, packages/spacecat-shared-data-access/test/it/generateSampleData.js, packages/spacecat-shared-data-access/test/unit/models/site-top-page.test.js, packages/spacecat-shared-data-access/test/unit/service/site-top-pages/index.test.js
In context for [SITES-22601](https://jira.corp.adobe.com/browse/SITES-22601) (auto fix broken backlinks), we need access to the keywords of a page to determine the best possible alternate url (as suggested [by research](https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=AEMSites&title=SEO+%7C+Broken+Backlinks+Auto-Suggest)) 
- **Request per page:**
Worst Case:
Each row in the query costs 12 Units (_sum_traffic_: 10, _keyword_: 1, _best_position_url_: 1)
Using a limit of 200 rows per request: 2400 Units (12 x 200).
For 200 broken backlinks: **480k Units** (2400 x 200)
- **For import:**
How many keywords should be imported?
For example, page with 20k keywords (with traffic):
Getting all keywords: **240k Units** (12 x 20 000)
Getting top 2k keywords: **24k Units** (12 x 2000)
=> feat: introduce organic keywords for ahrefs client and top keyword in top pages

package-lock.json, packages/spacecat-shared-data-access/src/models/site/audit-config-type.js, packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
This PR introduces the stored fixes of the broken backlinks so they can be shown in the UI and dowloaded by the user.
Implements: https://jira.corp.adobe.com/browse/SITES-22925
=> feat: introduce fixed URLs in audit type config

packages/spacecat-shared-utils/src/functions.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/test/functions.test.js
Introduce `isNonEmptyObject` method, which checks whether an object is an object and has properties of its own.
=> feat: isNonEmptyObject

packages/spacecat-shared-rum-api-client/src/functions/experiment.js, packages/spacecat-shared-rum-api-client/test/fixtures/bundles.json, packages/spacecat-shared-rum-api-client/test/fixtures/experiments.json
- click/convert/formsubmit metrics - each session can add 0/1 * (weight) at max to the metric count per selector - This answers which CTA was clicked
- add * to each metric, each session adding 0/1 * (weight), but with out selector - this answers whether there's click/convert/formsubmit event at all on the page, with out considering where it happened
- interactionsCount - a global property, 0/1 * (weight), if there's at least one click/convert/formsubmit per session
The example json from the test
```
{
"https://www.aem.live/home": [
{
"experiment": "short-home",
"variants": [
{
"name": "challenger-1",
"views": 1300,
"click": {
".hero": 100,
"*": 400,
".header #navmenu-0": 100,
".roi-calculator .button": 100,
".hero .button": 100
},
"convert": {},
"formsubmit": {},
"interactionsCount": 400 …
```
=> fix: Click count is artificially inflating the conversion rate

packages/spacecat-shared-data-access/src/index.d.ts
[SITES-23346](https://jira.corp.adobe.com/browse/SITES-23346
)
For consistency, would like to keep the export as getFailedCount().
Reference: https://github.com/adobe/spacecat-shared/blob/main/packages/spacecat-shared-data-access/src/dto/import-job.js#L39
=> fix: Fix the getFailedCount function in importJob interface

packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
Update Ahrefs broken backlinks filter to include links that where found outside the biggest piece of content on the page and links that have a nofollow attribute.
=> feat: update broken backlinks filter for ahrefs

packages/spacecat-shared-rum-api-client/src/functions/experiment.js, packages/spacecat-shared-rum-api-client/test/fixtures/bundles.json, packages/spacecat-shared-rum-api-client/test/fixtures/cwv.json, packages/spacecat-shared-rum-api-client/test/fixtures/experiments.json, packages/spacecat-shared-rum-api-client/test/fixtures/trafficSources.json
inferred start and end dates will track the oldest and latest bundle dates so that audit can set the experiment status.
Fixes [SITES-23657](https://jira.corp.adobe.com/browse/SITES-23657)
=> fix: updating inferred start and end dates to reflect old and latest from RUM bundles

packages/spacecat-shared-data-access/docs/schema.json, packages/spacecat-shared-data-access/src/dto/api-key.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/index.js, packages/spacecat-shared-data-access/src/models/api-key.js, packages/spacecat-shared-data-access/src/service/api-key/accessPatterns.js, packages/spacecat-shared-data-access/src/service/api-key/index.js, packages/spacecat-shared-data-access/src/service/index.js, packages/spacecat-shared-data-access/test/unit/models/api-key.test.js, packages/spacecat-shared-data-access/test/unit/service/api-key/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js
[SITES-23627](https://jira.corp.adobe.com/browse/SITES-23627)
Setup the dynamo DB table with the following attributes:
```
{  
"id": "298987DC-DEBC-45D2-9054-10053BF15F5E",  
"key": "(encrypted with crypto package)",  
"name": "Bruce's key",  
"imsUserId": "AD5E1C3F650AAAF30A495FD9@b13a68e1650aa8c6495ffe.e",  
"imsOrgId": "86DF666465096C340A495E89@AdobeOrg",
"createdAt": "2024-07-16T18:59:14.435Z",
"expiresAt": "2024-10-16T18:59:14.435Z",
"revokedAt": null,
"scopes": [    
{      "name": "import.write",
"domains": [        
"https://adobe.com"      
]    
}  
]
}
```
=> feat: Add API Key data attributes

packages/spacecat-shared-rum-api-client/src/index.d.ts, packages/spacecat-shared-rum-api-client/src/index.js, packages/spacecat-shared-rum-api-client/test/index.test.js
This PR introduces support for handling multiple queries in the RUM client, a feature necessary for opportunity detection.
The `queryMulti` method works by first fetching the RUM bundles once and then applying all requested queries to the retrieved raw data. This is to make sure the RUM Bundler API is only called once.
=> feat: multi-query support for rum-client

packages/spacecat-shared-data-access/test/unit/models/experiment.test.js
mistakenly used `getMilliseconds` instead of `getTime`, so the test was flaky
=> chore: fixing unit tests

packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/service/api-key/accessPatterns.js, packages/spacecat-shared-http-utils/src/auth/handlers/scoped-api-key.js
We're running into issues while using the ScopedApiHandler. It could be due to the invalid GSIPK here:
```
':gsi1pk': config.pkApiKey,
```
Logs we see on cloudwatch:
```
2024-08-14T18:06:35.170Z | 2024-08-14T18:06:35.170Z 77117fd4-5d26-403e-b159-baf06b6793d1 DEBUG Trying to authenticate with legacyApiKey
-- | --
  | 2024-08-14T18:06:35.172Z | 2024-08-14T18:06:35.172Z 77117fd4-5d26-403e-b159-baf06b6793d1 DEBUG Failed to authenticate with legacyApiKey
  | 2024-08-14T18:06:35.173Z2024-08-14T18:06:35.173Z	77117fd4-5d26-403e-b159-baf06b6793d1	DEBUG	Trying to authenticate with scopedApiKey | 2024-08-14T18:06:35.173Z 77117fd4-5d26-403e-b159-baf06b6793d1 DEBUG Trying to authenticate with scopedApiKey
  | 2024-08-14T18:06:35.176ZEND RequestId: 77117fd4-5d26-403e-b159-baf06b6793d1 | END RequestId: …
```
=> fix: add query changes

package-lock.json, packages/spacecat-shared-data-access/docs/schema.json, packages/spacecat-shared-data-access/src/dto/api-key.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/index.js, packages/spacecat-shared-data-access/src/models/api-key.js, packages/spacecat-shared-data-access/src/service/api-key/accessPatterns.js, packages/spacecat-shared-data-access/src/service/api-key/index.js, packages/spacecat-shared-data-access/test/unit/models/api-key.test.js, packages/spacecat-shared-data-access/test/unit/service/api-key/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js, packages/spacecat-shared-http-utils/package.json, packages/spacecat-shared-http-utils/src/auth/handlers/scoped-api-key.js, packages/spacecat-shared-http-utils/test/auth/auth-wrapper.test.js, packages/spacecat-shared-http-utils/test/auth/handlers/scoped-api-key.test.js
[SITES-23633](https://jira.corp.adobe.com/browse/SITES-23633)
- Refactor hashedKey to hashedApiKey for consistency with spacecat-api-service
- Modify the unit tests spacecat-shared-http-utils to remove dependency on spacecat-data-shared methods
- Modify the query - `getApiKeyByHashedApiKey` to return the first element of an array
=> fix: refactor hashed api key and query to retrieve API key

packages/spacecat-shared-data-access/src/dto/api-key.js, packages/spacecat-shared-http-utils/src/auth/handlers/scoped-api-key.js
Add `id` to ApiKeyDto. This might resolve the issue we are seeing with ApiKeys. ScopedApiKeyHandler abruptly stops.
Reference logs:
```
  | 2024-08-16T15:08:41.483Z | START RequestId: 64726ea5-b32b-4008-87a6-e072891f8460 Version: 1376
-- | -- | --
  | 2024-08-16T15:08:41.487Z | 2024-08-16T15:08:41.487Z 64726ea5-b32b-4008-87a6-e072891f8460 DEBUG Trying to authenticate with legacyApiKey
  | 2024-08-16T15:08:41.487Z | 2024-08-16T15:08:41.487Z 64726ea5-b32b-4008-87a6-e072891f8460 DEBUG Failed to authenticate with legacyApiKey
  | 2024-08-16T15:08:41.487Z | 2024-08-16T15:08:41.487Z 64726ea5-b32b-4008-87a6-e072891f8460 DEBUG Trying to authenticate with scopedApiKey
  | 2024-08-16T15:08:41.489Z | END RequestId: 64726ea5-b32b-4008-87a6-e072891f8460
```
=> fix: Add id to api-key DTO

packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
Required for adding a monthly/weekly audit that notifies internally about API units consumed
=> feat(ahrefs-client): get limits and usage for subscription

packages/spacecat-shared-data-access/test/it/db.test.js
While https://jira.corp.adobe.com/browse/SITES-24179 (see also https://cq-dev.slack.com/archives/C05A45JBP9N/p1723742180710369) is fixed, disabling temporarily the flaky IT tests, so we can get shared PRs and releases unrelated to the data access layer unblocked.
=> fix(tests): temporarily disable flaky tests

packages/spacecat-shared-http-utils/src/auth/authentication-manager.js, packages/spacecat-shared-http-utils/src/auth/handlers/scoped-api-key.js, packages/spacecat-shared-http-utils/test/auth/authentication-manager.test.js
Add try-catch block to authentication-manager to try and figure out the issue with ScopedApiKeyHandler
=> fix: add try-catch block to authentication manager

packages/spacecat-shared-data-access/test/it/db.test.js
- tests are using the `dataAccess.getSites()[0]` depending on the order sites are returned, this could be anything, so I've used the getSiteByBaseURL to get the same site object always
- `removes organization` it is removing the first organization, so most likely this is removing randomly, so getSites isn't returning the sites from this removed organization, which was causing the failure. So, I've moved the `removes organization` to the last in the file
=> fix: experimentation IT tests failing intermittently

packages/spacecat-shared-data-access/docs/schema.json, packages/spacecat-shared-data-access/src/dto/import-job.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/models/importer/import-job.js, packages/spacecat-shared-data-access/test/unit/models/importer/import-job.test.js, packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js
[SITES-23126](https://jira.corp.adobe.com/browse/SITES-23126)
Adding initiatedBy attribute to the importJob for analytics - to keep track of the jobs started by a user.
```
{
"id": "b6f08173-0e76-41d6-a7c8-213edee64353",
"baseURL": "https://www.canadiantire.ca",
"options": {
"enableJavascript": false,
"scrollToBottom": true
},
"startTime": "2024-08-19T20:15:37.121Z",
"status": "RUNNING",
"urlCount": 1,
"importQueueId": "spacecat-import-queue-1",
"initiatedBy": {
"name": 'test-user',
"imsUserId": 'test-ims-user-id',
"imsOrgId": 'test-ims-org-id',
"userAgent": 'Mozilla/5.0',
},
}
```
=> feat: add initiatedBy attribute to import job

package-lock.json, packages/spacecat-shared-data-access/src/models/site/config.js
Upon several naming discussions, we decided to change the name from product detail pages so something more generic.
=> fix: add property to include specific urls in the site config

packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
Update Ahrefs broken backlinks filter to include links that where found outside the biggest piece of content on the page and links that have a nofollow attribute.
Fix should have been delivered via https://github.com/adobe/spacecat-shared/pull/302, but that one was actually updating the get all backlinks (all, not only the broken ones) function.
=> fix(ahrefs-client): broken backlinks filter adjustment: do not limit to is do follow and is content

package-lock.json, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js, packages/spacecat-shared-data-access/src/service/import-url/index.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js
[SITES-24337](https://jira.corp.adobe.com/browse/SITES-24337)
We want to add a query to retrieve all URLs based on a jobId to generate an import report.
The discussion started here: https://github.com/adobe/spacecat-content-processor/pull/143#discussion_r1754542157
for this PR.
=> feat: Add a query to get all import urls by jobId

packages/spacecat-shared-data-access/src/models/audit.js, packages/spacecat-shared-data-access/test/unit/models/audit.test.js
Extend expiry date for audits from 1 to 6 months.
Temporarily until we clarify how to rollup and summarize the data based on reporting use cases.
=> fix(audits): extend expiry date for audits from 1 to 6 months

package-lock.json, packages/spacecat-shared-data-access/src/models/importer/import-url.js, packages/spacecat-shared-data-access/test/unit/models/importer/import-url.test.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js
[SITES-24645](https://jira.corp.adobe.com/browse/SITES-24645)
We want to add a validation check for jobId in spacecat-shared while creating an import-url.
We do not want an import-url entry in the DB without the jobId attribute.
=> SITES-24645: [Importer] Add validation check for jobId while creating an import URL

package-lock.json, packages/spacecat-shared-content-client/package.json, packages/spacecat-shared-content-client/src/clients/content-client.js, packages/spacecat-shared-content-client/test/clients/content-client.test.js
Feature to update redirects spreadsheet for an Edge Delivery Services website.
Receives a list of new redirects, validates them, ensuring they have the right format, and that they will not duplicate or create cycles with the existing redirect rules, and appends them to the existing rules in the spreadsheet.
=> feat: update redirects

packages/spacecat-shared-data-access/src/models/api-key.js
[SITES-22756](https://jira.corp.adobe.com/browse/SITES-22756)
Add an additional scope `'imports.write_all_domains'` to allow imports on all domains.
=> feat: Add an additional scope to all imports on all domains

package-lock.json, packages/spacecat-shared-data-access/docs/schema.json, packages/spacecat-shared-data-access/src/dto/audit.js, packages/spacecat-shared-data-access/src/dto/dto-utils.js, packages/spacecat-shared-data-access/src/dto/import-url.js, packages/spacecat-shared-data-access/src/models/importer/import-url.js, packages/spacecat-shared-data-access/test/it/db.test.js, packages/spacecat-shared-data-access/test/unit/models/importer/import-url.test.js
Adds an `expiresAt` field to import-url entities which will be leveraged by Dynamo to automatically remove items after their TTL has elapsed.
- [SITES-23373](https://jira.corp.adobe.com/browse/SITES-23373)
=> feat: Expire URLs automatically after set period of time

packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Fix a bug where an undefined handler config would throw an error.
https://cq-dev.slack.com/archives/C06AVLUPML5/p1728172881655109
=> fix: gracefully handle config in case handler is not defined

package-lock.json, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/models/api-key.js, packages/spacecat-shared-data-access/src/service/import-job/accessPatterns.js, packages/spacecat-shared-data-access/src/service/import-job/index.js, packages/spacecat-shared-data-access/src/service/import-url/accessPatterns.js, packages/spacecat-shared-data-access/test/it/db.test.js, packages/spacecat-shared-data-access/test/unit/models/api-key.test.js, packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js, packages/spacecat-shared-data-access/test/unit/service/import-url/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js
Implements `removeImportJob`, which removes the import job and all associated import url entities.
Add new `imports.delete` scope to restrict import job deletion to API keys with the relevant scope.
- [SITES-26088](https://jira.corp.adobe.com/browse/SITES-26088)
=> feat: Support import job deletion

package-lock.json, packages/spacecat-shared-utils/package.json, packages/spacecat-shared-utils/src/adobe-fetch.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/index.js, packages/spacecat-shared-utils/src/tracing-fetch.js, packages/spacecat-shared-utils/test/index.test.js, packages/spacecat-shared-utils/test/tracing-fetch.test.js
Add a wrapped fetch with minimal tracing support. Unfortunately we can't use the `AWSXRay` SDKs global instrumentation due to: https://github.com/aws/aws-xray-sdk-node/issues/487 otherwise documented at https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-httpclients.html
=> feat: tracing fetch

package-lock.json, packages/spacecat-shared-utils/src/sqs.js, packages/spacecat-shared-utils/test/sqs.test.js
Add support for passing a `MessageGroupId` to the `sqsClient.send(..)` method to enable the use of FIFO queues.
Without this property we see the following error in the logs:
```
...failed with error: MissingParameter: The request must contain the parameter MessageGroupId.
```
- [SITES-26422](https://jira.corp.adobe.com/browse/SITES-26422) Migrate all import queues to FIFO SQS queues
=> feat: support FIFO queues with the SQS sendMessage helper

packages/spacecat-shared-data-access/src/models/configuration.js, packages/spacecat-shared-data-access/test/unit/models/configuration.test.js
Currently, some audit data in the database has an incomplete structure.
For example, broken-internal-links:
```
"broken-backlinks-internal": {
"enabledByDefault": true,
"disabled": {
"sites": [
"site-id",
],
// missed orgs
},
},
```
The absence of the "orgs/sites" key leads to an error in
https://github.com/adobe/spacecat-shared/blob/main/packages/spacecat-shared-data-access/src/models/configuration.js#L39-L45
https://spacecat.coralogix.com/#/query-new/logs?id=qzf80Nda2AaKpjA4VSTle&page=0
```
TypeError: Cannot read properties of undefined (reading 'includes')
at Configuration.self.isHandlerEnabledForSite (/var/task/index.js:8360:77)
```
This PR includes the corrected logic to handle such cases.
=> fix: handle missing 'sites' and 'orgs' in enabled/disabled configuraions safely

packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
My PR did not have the `feat` prefix and so it wasn't deployed.  I didn't realize that was the mechanism.  Is that worth a description in `pull_request_template.md`?
This is a quick correction to some JavaDocs but essentially is to have the GPT package deployed.
https://jira.corp.adobe.com/browse/SITES-26591
PR: https://github.com/adobe/spacecat-shared/pull/422
=> feat: SITES-26591 [Import Assistant] Expand GPT client to user chat endpoint

packages/spacecat-shared-data-access/src/models/api-key/api-key.js, packages/spacecat-shared-data-access/test/unit/models/api-key.test.js
Introduce the `imports.assistant` scope for the API key to enable calls to the assistant, providing help when creating Import JS.
Jira: https://jira.corp.adobe.com/browse/SITES-26835
=> feat: SITES-26835 [Import Assistant] Introduce imports.assistant api key scope

packages/spacecat-shared-http-utils/src/index.js, packages/spacecat-shared-http-utils/test/index.test.js
[SITES-25915](https://jira.corp.adobe.com/browse/SITES-25915)
Add unauthorized and forbidden to the http status code as discussed in this comment: https://github.com/adobe/spacecat-api-service/pull/569/files#r1841073366
=> feat: Add unauthorized and forbidden to https status codes

package-lock.json, packages/spacecat-shared-utils/src/url-helpers.js
business.adobe.com has bot protection and we cannot resolve the audit url to run the broken-backlinks audit
=> fix: resolving url when site has bot protection

packages/spacecat-shared-gpt-client/README.md, packages/spacecat-shared-gpt-client/src/clients/firefall-client.js, packages/spacecat-shared-gpt-client/test/clients/firefall-client.test.js
The context's IMS_CLIENT_ID value is used in 2 places:
- IMSClient: IMS Token fetch (as an IMS Client Id)
- GPTClient: Firefall call as the `x-gw-ims-org-id` header value
This PR is to allow the `x-gw-ims-org-id` to use a specified, optional value.
https://jira.corp.adobe.com/browse/SITES-26948
=> fix: SITES-26948 [Import Assistant] Allow calls to Firefall to use specified ims org id

package-lock.json, packages/spacecat-shared-data-access/src/dto/audit.js, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/test/unit/service/audits/index.test.js
In context of the new opportunity and suggestions data model, it is a requirement for the audits to have an ID in order to link them to an opportunity.
=> feat: introduce missing audit id property

packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js, packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
form vitals output would now include form button clicks.
```
{
"url": "https://business.adobe.com/jp/resources/reports/retail-digital-trends.html",
"formsubmit": {
"desktop:windows": 100
},
"formview": {
},
"formengagement": {
"desktop:windows": 100
},
"formbuttonclick": {
"desktop:windows": 100
},
"pageview": {
"desktop:windows": 100
}
}
```
=> feat: introduce form button clicks in form vitals

packages/spacecat-shared-utils/src/sqs.js
"_Function was not invoked properly, message body is not a valid JSON_" errors are not actual errors creating unnecessary noise in the ops alerts
hence, decreasing the level to warn
=> fix(sqs-wrapper): decrease error log level

package-lock.json, packages/spacecat-shared-data-access/package.json, packages/spacecat-shared-data-access/src/index.d.ts, packages/spacecat-shared-data-access/src/service/site-candidates/accessPatterns.js, packages/spacecat-shared-data-access/src/service/site-candidates/index.js, packages/spacecat-shared-data-access/test/it/index.test.js, packages/spacecat-shared-data-access/test/unit/service/index.test.js, packages/spacecat-shared-data-access/test/unit/service/site-candidates/index.test.js
adds `getSiteCandidates` access pattern
=> feat(data-access): get site candidates

package-lock.json, packages/spacecat-shared-utils/src/sqs.js, packages/spacecat-shared-utils/test/sqs.test.js
Currently, sending an SQS message to a standard (non-FIFO) queue will fail if the `messageGroupId` param is provided to the `sendMessage` function. The function should only include this param when it is sending a message to a FIFO queue.
- #489
=> fix(sqs): Support both standard and FIFO SQS queues

packages/spacecat-shared-data-access/src/v2/models/base/base.model.js, packages/spacecat-shared-data-access/test/it/opportunity/opportunity.test.js, packages/spacecat-shared-data-access/test/it/site-top-page/site-top-page.test.js, packages/spacecat-shared-data-access/test/it/util/db.js, packages/spacecat-shared-data-access/test/unit/v2/models/base/base.model.test.js
- make sure parent record is not removed if any of the child records fails to remove
- add more IT tests
=> fix: dependent remove errors, more tests

package-lock.json, packages/spacecat-shared-data-access/src/models/api-key/api-key.schema.js, packages/spacecat-shared-data-access/src/util/patcher.js, packages/spacecat-shared-data-access/test/it/organization/organization.test.js, packages/spacecat-shared-data-access/test/unit/util/patcher.test.js
- Patcher should use the attribute's schema getter to provide valid updated values on updating an entity
- Missing schema elements
=> fix: patcher should use schema getter, schema omissions

packages/spacecat-shared-utils/src/sqs.js, packages/spacecat-shared-utils/test/sqs.test.js
This is to prevent ops alerts when no messages are in the payload.
=> fix: improve sqs event adapter error handling

packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js, packages/spacecat-shared-rum-api-client/test/common/rum-bundler-client.test.js, packages/spacecat-shared-rum-api-client/test/index.test.js
as per https://cq-dev.slack.com/archives/C07198KKQ07/p1736898652490009
=> fix(rum-api-client): point to the new rum bundler host

packages/spacecat-shared-utils/src/helpers.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/test/helpers.test.js
Moving from https://github.com/adobe/spacecat-content-processor/
=> feat: introduce replace placeholders for prompts

packages/spacecat-shared-utils/src/formcalc.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/index.js, packages/spacecat-shared-utils/test/formcalc.test.js, packages/spacecat-shared-utils/test/index.test.js
=> feat: add utility api for forms metrics

packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/url-helpers.js, packages/spacecat-shared-utils/test/url-helpers.test.js
There are pages that need to specify a user agent, others fail when there is a custom user agent:
https://spacecat.coralogix.com/#/query-new/logs?id=hAC93giMyiLuiHMxw9VW3&page=0
The idea is to add the user agent to the site configuration, then the consumer of the function can decide weather to add a user agent or not
=> fix: composeAuditURL user agent failing for some sites

.gitignore, package-lock.json, packages/spacecat-shared-data-access/src/models/import-job/import-job.model.js, packages/spacecat-shared-data-access/src/models/import-job/import-job.schema.js, packages/spacecat-shared-data-access/test/it/import-job/import-job.test.js, packages/spacecat-shared-data-access/test/unit/models/import-job/import-job.model.test.js
To include support for crosswalk imports, we need to define `type` property in our options field.  The value for type can either be 'xwalk' or 'doc'.  The schema needs to be updated to support this new property.
=> fix(sites-28856): update shared-data schema to include type in options

.vscode/settings.json, package-lock.json, packages/spacecat-shared-ahrefs-client/src/index.d.ts, packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
Implements: https://jira.corp.adobe.com/browse/SITES-28786
I didn't find any consumer for the existing organic keywords query/import, so I propose to adjust/enhance it with the requirements we have for HOTLCTR opportunity.
=> fix(ahrefs-client): enhance organic keywords query to use in HOTLCTR opportunity

packages/spacecat-shared-utils/package.json, packages/spacecat-shared-utils/src/helpers.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/index.js, packages/spacecat-shared-utils/test/helpers.test.js, packages/spacecat-shared-utils/test/index.test.js
In #579 comments, @solaris007 suggested handling queries as static files, external to the javascript source.  The getPrompt helper function was mentioned as a model.  This PR will create an updated release of the spacecat-shared-utils package which can be referenced by #579.
=> feat: util for reading .query static files, modeled after getPrompt

packages/spacecat-shared-data-access/src/models/site/site.schema.js
For AEM CS we need additional configuration similar to hlxConfig.
For now we need programId, environmentId, authorURL, and siteId (which is an AEM CS id for the site).
I assume the easiest is to just add a container object to the site object - the contents is then delivery type specific
=> Add delivery configuration object to site object

packages/spacecat-shared-data-access/src/models/audit/audit.model.js, packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
In preparation for adding step support to the `audit-worker`, the audit model should express the supported destinations to which audit steps can chain, including expected payloads.
Also see: https://github.com/adobe/spacecat-audit-worker/pull/659
=> feat: audit step destinations

packages/spacecat-shared-data-access/src/models/site/index.d.ts, packages/spacecat-shared-data-access/src/models/site/site.schema.js, packages/spacecat-shared-data-access/test/fixtures/sites.fixture.js, packages/spacecat-shared-data-access/test/it/site/site.test.js, packages/spacecat-shared-data-access/test/unit/models/site/site.model.test.js
Problem: 
PSS UI is rendering baseURL in several places. We need human friendly name for each site to render on all the pages in PSS UI. This PR adds a name attribute in Site schema and changes to update from PATCH call. 
spacecat-api-service changes - https://github.com/adobe/spacecat-api-service/pull/752
Request: 
`curl --request PATCH \
--url https://spacecat.experiencecloud.live/api/ci/sites/{siteId} \
--header 'Content-Type: application/json' \
--header 'authorization: Bearer <token>' \
--data '{
"name": "SITE NAME"
}'`
Response: 
`{
"id": "123",
"baseURL": "https://example.com",
"name": "SITE NAME",
"hlxConfig": {},
"deliveryType": "aem_cs",
"organizationId": "org-id",
"isLive": false,
"isLiveToggledAt": "2025-01-07T10:54:22.455Z",
"createdAt": "2025-01-07T10:54:22.453Z", …
=> feat: adds site name

packages/spacecat-shared-data-access/src/models/audit/audit.model.js, packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
- [ASSETS-47752 | [Backend] Extract alt-text audit type constant to spacecat-shared](https://jira.corp.adobe.com/browse/ASSETS-47752)
- [ASSETS-47238 | [Epic] Alt text audit for Project Success Studio](https://jira.corp.adobe.com/browse/ASSETS-47238)
=> feat: add alt-text audit type constant

packages/spacecat-shared-data-access/src/models/organization/organization.model.js, packages/spacecat-shared-data-access/src/models/organization/organization.schema.js, packages/spacecat-shared-data-access/test/fixtures/organizations.fixture.js, packages/spacecat-shared-data-access/test/it/organization/organization.test.js, packages/spacecat-shared-data-access/test/unit/models/organization/organization.model.test.js
Validates the IMS Org ID for the Organization model. Also adds a constant to the Organization model with the IMS Org ID regex for consumers to leverage for similar checks.
=> fix: validate IMS Org ID

packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/index.js, packages/spacecat-shared-utils/src/tracing-fetch.js, packages/spacecat-shared-utils/test/index.test.js, packages/spacecat-shared-utils/test/tracing-fetch.test.js
Sets the default user agent for `tracingFetch`. Also exports a constant with the user agent for use by consuming code.
=> feat: set default fetch user-agent

.github/actions/lint-test-coverage/action.yaml, .vscode/settings.json, package-lock.json, packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/src/models/site/index.d.ts, packages/spacecat-shared-data-access/test/fixtures/sites.fixture.js, packages/spacecat-shared-data-access/test/it/site/site.test.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Add schema to site/org config detailing the supported import types and their configuration. Adds utility methods to enable/disable imports.
=> feat: import config schema

package-lock.json, packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/fixtures/sites.fixture.js, packages/spacecat-shared-data-access/test/it/site/site.test.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
The import schema update introduced via #626 accidentally set the newly introduce `enabled` property as required. this caused already existing import configurations in the database to be invalid, causing outages. The `enabled` flag is now optional. Relevant unit and IT tests have been enhanced.
=> fix: import-schema backwards compatibility

packages/spacecat-shared-gpt-client/src/clients/firefall-client.js, packages/spacecat-shared-gpt-client/test/clients/firefall-client.test.js
We need a way to see why Firefall is refusing some requests. Current error message is swallowed and not delivered to consumer.
This passes message across when available.
https://jira.corp.adobe.com/browse/ASSETS-47371
=> fix: improves logs for FF client failures

packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
When updating the site config with `url`, failing with 
```
Handler exception after 122 ms. Path: /sites/cd6528f6-fd7d-4003-a08e-d4d0c34632c5 Error: Configuration validation error: "imports[0]" does not match any of the allowed types
at validateConfiguration (/var/task/index.js:20949:11)
at Config (/var/task/index.js:20956:23)
at get (/var/task/index.js:21320:71)
at Attribute.get (/var/task/index.js:157778:14)
at #set (/var/task/index.js:22220:39)
at Patcher.patchValue (/var/task/index.js:22300:14)
at <computed> [as setConfig] (/var/task/index.js:16907:26)
at updateSite (/var/task/index.js:398214:12)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async run (/var/task/index.js:400365:14) {
[cause]: [Error [ValidationError]: "imports[0]" does not match any …
```
=> fix: url override in import-schema

package-lock.json, packages/spacecat-shared-data-access/src/models/configuration/configuration.model.js, packages/spacecat-shared-data-access/test/fixtures/configurations.fixture.js, packages/spacecat-shared-data-access/test/unit/models/configuration/configuration.model.test.js
Introduce `getEnabledAuditsForSite` for the bulk audit run command.
=> feat: introduce getEnabledAuditsForSite in the configuration model

package-lock.json, packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
`all-traffic` is implemented in https://github.com/adobe/spacecat-import-worker/pull/240
=> fix: add all-traffic to import schema

package-lock.json, packages/spacecat-shared-utils/src/tracing-fetch.js, packages/spacecat-shared-utils/test/tracing-fetch.test.js
Introduce capability to set timeout for requests using `tracingFetch`. Default timeout is set to 10s.
=> feat: tracing fetch timeout

packages/spacecat-shared-data-access/src/models/base/base.collection.js, packages/spacecat-shared-data-access/test/unit/models/base/base.collection.test.js
=> feat(data-access): fetch all records on demand

packages/spacecat-shared-data-access/README.md, packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Adds proper validation for the `contentAiConfig` property in the `Config` class within the `spacecat-shared-data-access` package by:
- Adding schema validation for `contentAiConfig` with required key and index fields
- Adding a getter method `getContentAiConfig()` to access the configuration
- Adding a default empty object for `contentAiConfig` in `DEFAULT_CONFIG`
- Updating the `toDynamoItem` method
Testing
- Added unit tests for contentAiConfig validation
[Spacecat ContentAI Config](https://git.corp.adobe.com/orgs/experience-platform/projects/16?pane=issue&itemId=12200)
=> feat: Add contentAiConfig validation to Config class

packages/spacecat-shared-data-access/src/models/audit/audit.model.js, packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
Adding missing `completionUrl` so the audit worker can be triggered back after the scraper executes.
Adding `allowCache` property for both the importer and scraper to return the already existing content instead of triggering an import/scrape again for every audit.
=> fix: completionUrl not sent to content scraper and introduce skip property

packages/spacecat-shared-content-client/src/clients/content-client.js, packages/spacecat-shared-content-client/test/clients/content-client.test.js
Adds a `getResourcePath()` method to `ContentClient` which returns resource paths for page URL paths.
- https://jira.corp.adobe.com/browse/SITES-30735
=> feat: Add `ContentClient.prototype.getResourcePath`

packages/spacecat-shared-data-access/src/models/base/base.collection.js, packages/spacecat-shared-data-access/test/unit/models/base/base.collection.test.js
https://jira.corp.adobe.com/browse/SITES-30735
=> fix: collection._saveMany deals with empty `.unprocessed` array in response

packages/spacecat-shared-http-utils/src/index.d.ts, packages/spacecat-shared-http-utils/src/index.js, packages/spacecat-shared-http-utils/test/index.test.js
https://jira.corp.adobe.com/browse/SITES-31201
Adds a new `accepted()` function to the HTTP utilities to support HTTP 202 Accepted responses. This status code is commonly used for asynchronous operations where the request has been accepted for processing but the processing has not been completed.
Changes:
- Added `accepted()` function to create 202 responses
- Added TypeScript type declaration for the new function
- Added unit tests to verify the function behavior
The function follows the same pattern as other response helpers like `created()` and `ok()`, providing a consistent API for creating HTTP responses.
=> feat(http-utils): add HTTP 202 Accepted response helper

package-lock.json, packages/spacecat-shared-utils/package.json, packages/spacecat-shared-utils/src/auth.js, packages/spacecat-shared-utils/src/index.d.ts, packages/spacecat-shared-utils/src/index.js, packages/spacecat-shared-utils/test/auth.test.js, packages/spacecat-shared-utils/test/index.test.js
https://jira.corp.adobe.com/browse/SITES-31664
This PR introduces a new authentication utility function that securely retrieves page authentication tokens for sites using AWS Secrets Manager.
=> Add Page Authentication Token Retrieval Functionality

packages/spacecat-shared-data-access/src/models/async-job/async-job.schema.js, packages/spacecat-shared-data-access/src/models/async-job/index.d.ts, packages/spacecat-shared-data-access/test/unit/models/async-job/async-job.model.test.js
extend async job result to accept an array
=> fix: async job schema

packages/spacecat-shared-ahrefs-client/src/index.d.ts, packages/spacecat-shared-ahrefs-client/src/index.js, packages/spacecat-shared-ahrefs-client/test/index.test.js
Adds an `excludeBranded` option to `AhrefsAPIClient#getOrganicKeywords` to exclusively retreive unbranded keywords from Ahrefs.
This is required for Project Elmo
=> feat: Support fetching only unbranded keywords from ahrefs

package-lock.json, packages/spacecat-shared-data-access/package.json, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js, packages/spacecat-shared-http-utils/src/index.d.ts, packages/spacecat-shared-http-utils/src/index.js, packages/spacecat-shared-http-utils/test/index.test.js
- Adding `methodNotAllowed` http response util.
- Adding `createResponse` type def that was missing
- Update to latest `spacecate-shared-utils`
- Fix package lock
- Fix unrelated failing test
=> feat: add 405 response util

packages/spacecat-shared-gpt-client/src/clients/firefall-client.js, packages/spacecat-shared-gpt-client/src/clients/genvar-client.js, packages/spacecat-shared-gpt-client/src/utils.js
Fixes hackathon remnant where unsanitized headers were logged: `Authorization` and `x-api-key`. Introduces small util function to sanitize such headers.
=> fix: sanitize headers before logging

packages/spacecat-shared-rum-api-client/src/functions/opportunities/high-organic-low-ctr.js, packages/spacecat-shared-rum-api-client/src/functions/traffic-acquisition.js, packages/spacecat-shared-rum-api-client/test/fixtures/high-organic-low-ctr.json, packages/spacecat-shared-rum-api-client/test/functions.test.js
https://jira.corp.adobe.com/browse/SITES-31498
Since we're not having enough high-organic-low-ctr opportunities due to our thresholds, the recommendation from leadership is to remove the thresholds ([slack thread](https://cq-dev.slack.com/archives/C05A45JBP9N/p1750161326304269)), this PR 
- removes the existing thresholds
- sorts the pages by overall traffic and earned traffic, creates a percentileScore to sort the high overall and earned traffic pages to the top
- Returns top 10 pages as high-organic-low-ctr opportunity
- This will guarantee that we'll always have 10 high impact pages based on the traffic to generate the content
=> feat: high organic low ctr detection using traffic instead of thresholds

packages/spacecat-shared-rum-api-client/README.md, packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js, packages/spacecat-shared-rum-api-client/src/index.d.ts, packages/spacecat-shared-rum-api-client/test/common/rum-bundler-client.test.js
[SITES-32914](https://jira.corp.adobe.com/browse/SITES-32914)
Added support for custom date ranges in the RUM API client by implementing `startTime` and `endTime` parameters. This enhancement allows users to query RUM data for specific date ranges instead of being limited to interval-based queries.
- **`startTime`** and **`endTime`** parameters in ISO 8601 format (e.g., `"2024-01-01T00:00:00Z"`)
- **Priority over interval**: When both `startTime`/`endTime` and `interval` are provided, date range takes precedence
- **Backward compatibility**: Existing interval-based queries continue to work unchanged
- **Granularity support**: Works with both `daily` and `hourly` granularities
- New `generateUrlsForDateRange()` function for custom date range URL generation
- Proper handling of cross-month …
=> feat: SITES-32914 implement `startDate` and `endDate` in RUM client

packages/spacecat-shared-data-access/src/models/import-job/import-job.model.js, packages/spacecat-shared-data-access/test/it/import-job/import-job.test.js
To include support for da imports, we need to define type property in our options field. The value for type can either be 'xwalk' or 'doc' or 'da'. The schema needs to be updated to support this new property.
* Parent issue for supporting DA import in EC : https://github.com/Adobe-AEM-Foundation/site-transfer-agent-import/issues/59
=> fix: Update shared-data schema to include 'da' type in options

packages/spacecat-shared-data-access/src/models/site/index.d.ts, packages/spacecat-shared-data-access/src/models/site/site.schema.js, packages/spacecat-shared-data-access/test/fixtures/sites.fixture.js, packages/spacecat-shared-data-access/test/it/site/site.test.js, packages/spacecat-shared-data-access/test/unit/models/site/site.model.test.js
For Sandboxing efforts, we required to have a site config which can help us to know if a site is sandbox or not, which will help in updating the UI accordingly for those sites.
=> feat: introduce isSandbox flag for sandbox sites

packages/spacecat-shared-data-access/src/models/site/config.js, packages/spacecat-shared-data-access/src/models/site/index.d.ts, packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Summary:
- introduces LLMO URL patterns
- removes `country` and `product` fields from LLMO questions
- replaces these with "well known tags" and adds extraction logic
- https://jira.corp.adobe.com/browse/LLMO-19
- https://jira.corp.adobe.com/browse/LLMO-94
=> feat: amend llmo config with URL patterns

packages/spacecat-shared-data-access/src/models/configuration/configuration.model.js
Add `'never'` as a valid value for job intervals.
This enables activating imports for sites without ever having them scheduled by `spacecat-job-dispatcher`.
That's useful for imports that are invoked manually via the `@spacecat` bot or triggered by audits.
For ahrefs-based imports specifically, this is meant to drive down the consumption of Ahrefs API Units.
https://jira.corp.adobe.com/browse/LLMO-186
=> Add `'never'` to job intervals

packages/spacecat-shared-data-access/src/models/audit/audit.model.js, packages/spacecat-shared-data-access/src/models/configuration/configuration.model.js
Add `'never'` as a valid value for job intervals.
This enables activating imports for sites without ever having them scheduled by `spacecat-job-dispatcher`.
That's useful for imports that are invoked manually via the `@spacecat` bot or triggered by audits.
For ahrefs-based imports specifically, this is meant to drive down the consumption of Ahrefs API Units.
https://jira.corp.adobe.com/browse/LLMO-186
=> feat: Add `'never'` to job intervals (#885)

packages/spacecat-shared-rum-api-client/README.md, packages/spacecat-shared-rum-api-client/src/functions/opportunities/high-organic-low-ctr.js, packages/spacecat-shared-rum-api-client/test/functions.test.js
Making maximum opportunities returned configurable using handler `options`
Required for https://github.com/adobe/spacecat-audit-worker/pull/1086
=> fix: make max opportunities configurable

packages/spacecat-shared-utils/src/aem-content-api-utils.js, packages/spacecat-shared-utils/test/aem-content-api-utils.test.js
fix: need to switch to /adobe/pages because experimental endpoints do not exist in AMS
=> fix: need to switch to /adobe/pages because experimental endpoints do not exist in AMS

packages/spacecat-shared-data-access/src/models/audit/audit.model.js
allow import step to configure cache or no cache, keeping default true if not passed
=> fix: allow configurable cache flag on import step
