- .circleci/config.yml
- .github/workflows/semantic-release.yaml
- .releaserc.cjs
- package-lock.json
- package.json
- packages/spacecat-shared-rum-api-client/test/rum-api-client.test.js
- renovate.json5
> fix: update node to lts/20, semantic release, misc

- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/service/organizations/accessPatterns.js
- packages/spacecat-shared-data-access/src/service/sites/accessPatterns.js
- packages/spacecat-shared-data-access/src/service/sites/index.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/unit/service/index.test.js
- packages/spacecat-shared-data-access/test/unit/service/sites/index.test.js
In preparation for adding the API controller to api-service, i am adding a couple of data layer things that are missing for the organizations model.
> fix: add missing org data layer methods

- packages/spacecat-shared-rum-api-client/README.md
- packages/spacecat-shared-slack-client/src/index.d.ts
> fix: add missing type declaration for SLACK_TARGETS

- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/test/helpers.test.js
> fix: secrets resolve ci versions properly

- packages/spacecat-shared-slack-client/README.md
- packages/spacecat-shared-slack-client/package.json
- packages/spacecat-shared-slack-client/src/clients/base-slack-client.js
- packages/spacecat-shared-slack-client/src/clients/elevated-slack-client.js
- packages/spacecat-shared-slack-client/src/clients/index.d.ts
- packages/spacecat-shared-slack-client/src/index.d.ts
- packages/spacecat-shared-slack-client/src/index.js
- packages/spacecat-shared-slack-client/src/models/index.d.ts
- packages/spacecat-shared-slack-client/src/models/slack-channel.js
- packages/spacecat-shared-slack-client/src/models/slack-team.js
- packages/spacecat-shared-slack-client/src/models/slack-user.js
- packages/spacecat-shared-slack-client/test/clients/base-slack-client.test.js
- packages/spacecat-shared-slack-client/test/clients/elevated-slack-client.test.js
- packages/spacecat-shared-slack-client/test/index.test.js
This PR introduces significant enhancements to the `@adobe/spacecat-shared-slack-client` package. The focus is on  added functionalities for channel creation and user invitations in the context of SpaceCat handling collaboration channel creation for fulfillment events as well as when requested via HTTP API for select clients, such as Cloudmanager.
1. **Channel Management**: Functionality to create new Slack channels, with options for setting the channel's topic, description, and privacy settings. For each created channel, configurable ops admins are invited.
2. **User Invitations**: A feature to invite users to Slack channels via email, catering to various user states like existing users, users not in channel, and non-workspace members, as well as users needing upgrade from single-channel …
> feat: slack channel management

- package-lock.json
- packages/spacecat-shared-gpt-client/.jsdoc.json
- packages/spacecat-shared-gpt-client/.mocha-multi.json
- packages/spacecat-shared-gpt-client/.npmignore
- packages/spacecat-shared-gpt-client/.nycrc.json
- packages/spacecat-shared-gpt-client/.releaserc.cjs
- packages/spacecat-shared-gpt-client/CODE_OF_CONDUCT.md
- packages/spacecat-shared-gpt-client/CONTRIBUTING.md
- packages/spacecat-shared-gpt-client/LICENSE.txt
- packages/spacecat-shared-gpt-client/README.md
- packages/spacecat-shared-gpt-client/package.json
- packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
- packages/spacecat-shared-gpt-client/src/clients/index.d.ts
- packages/spacecat-shared-gpt-client/src/index.d.ts
- packages/spacecat-shared-gpt-client/src/index.js
- packages/spacecat-shared-gpt-client/src/utils.js
- packages/spacecat-shared-gpt-client/test/clients/firefall-client.test.js
- packages/spacecat-shared-gpt-client/test/setup-env.js
Adds a simple client to send a prompt to the Firefall API and get the response back.
> feat: firefall client

- package-lock.json
- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/s3.js
- packages/spacecat-shared-utils/test/s3.test.js
> feat: introduce AWS S3 wrapper

- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/src/url-helpers.js
- packages/spacecat-shared-utils/test/index.test.js
- packages/spacecat-shared-utils/test/url-helpers.test.js
> feat: url helpers in utils

- packages/spacecat-shared-data-access/README.md
- packages/spacecat-shared-data-access/src/dto/site-candidate.js
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/service/site-candidates/accessPatterns.js
- packages/spacecat-shared-data-access/src/service/site-candidates/index.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/unit/service/index.test.js
- packages/spacecat-shared-data-access/test/unit/service/site-candidates/index.test.js
- added method `getSiteCandidateByBaseURL` to `dataAccess`
> fix: retrieve site candidate

- packages/spacecat-shared-data-access/src/models/site-candidate.js
- packages/spacecat-shared-data-access/test/unit/models/site-candidate.test.js
> fix: site-candidate should not have id

- packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
> fix: waiting job status

- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/src/sqs.js
- packages/spacecat-shared-utils/test/index.test.js
- packages/spacecat-shared-utils/test/sqs.test.js
> fix: sqsWrapper not properly exported

- packages/spacecat-shared-data-access/src/models/audit.js
> fix: add experimentation type audit

- package-lock.json
- packages/spacecat-shared-ims-client/.jsdoc.json
- packages/spacecat-shared-ims-client/.mocha-multi.json
- packages/spacecat-shared-ims-client/.npmignore
- packages/spacecat-shared-ims-client/.nycrc.json
- packages/spacecat-shared-ims-client/.releaserc.cjs
- packages/spacecat-shared-ims-client/CODE_OF_CONDUCT.md
- packages/spacecat-shared-ims-client/CONTRIBUTING.md
- packages/spacecat-shared-ims-client/LICENSE.txt
- packages/spacecat-shared-ims-client/README.md
- packages/spacecat-shared-ims-client/package.json
- packages/spacecat-shared-ims-client/src/clients/ims-client.js
- packages/spacecat-shared-ims-client/src/clients/index.d.ts
- packages/spacecat-shared-ims-client/src/index.d.ts
- packages/spacecat-shared-ims-client/src/index.js
- packages/spacecat-shared-ims-client/src/utils.js
- packages/spacecat-shared-ims-client/test/clients/ims-client.test.js
- packages/spacecat-shared-ims-client/test/clients/ims-sample-responses.js
- packages/spacecat-shared-ims-client/test/clients/ims-sample-return-values.js
- packages/spacecat-shared-ims-client/test/setup-env.js
IMS Client
Blocks https://github.com/adobe/spacecat-fulfillment-worker/pull/2
> feat: ims client (WIP)

- package-lock.json
- packages/spacecat-shared-ims-client/README.md
- packages/spacecat-shared-ims-client/package.json
- packages/spacecat-shared-ims-client/src/clients/ims-client-wrapper.js
- packages/spacecat-shared-ims-client/src/clients/ims-client.js
- packages/spacecat-shared-ims-client/src/clients/index.d.ts
- packages/spacecat-shared-ims-client/src/utils.js
- packages/spacecat-shared-ims-client/test/clients/ims-client-wrapper.test.js
- add lambda wrapper
- pr feedback from previous PR
> feat: IMS Client Wrapper

- packages/spacecat-shared-utils/src/index.d.ts
> fix: composeAuditUrl docs

- packages/spacecat-shared-data-access/src/models/organization.js
- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/it/generateSampleData.js
- packages/spacecat-shared-data-access/test/unit/models/organization.test.js
- packages/spacecat-shared-data-access/test/unit/models/site.test.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
> feat: audit-config support for organizations

- packages/spacecat-shared-data-access/src/models/site.js
- packages/spacecat-shared-data-access/test/unit/models/site.test.js
> fix: update config packaging for site

- package-lock.json
- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/helpers.test.js
- packages/spacecat-shared-utils/test/index.test.js
> feat: helper to detect audits are disabled

- packages/spacecat-shared-data-access/src/models/site-candidate.js
- packages/spacecat-shared-data-access/src/models/site.js
> fix: include invalid base url in error message

- package-lock.json
- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/test/helpers.test.js
https://github.com/adobe/spacecat-api-service/issues/210
https://github.com/adobe/spacecat-api-service/pull/214
> feat: add json to csv helper function

- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/index.test.js
Export `generateCSVFile` function from https://github.com/adobe/spacecat-shared/pull/185
> Json to csv export

- packages/spacecat-shared-data-access/src/models/audit.js
- packages/spacecat-shared-data-access/test/unit/models/audit.test.js
> fix: audit result can be an array

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Ticket #195 
Add `invitedUserCount` to Slack config.
> feat: Track number of users invited to Slack #195

- packages/spacecat-shared-slack-client/src/wrappers/elevated-client-wrapper.js
Hoping this PR, with a lowercase `feat`, will trigger the release that the original PR did not (#199).
> feat: trigger a release of the spacecat-shared-ims-client package

- packages/spacecat-shared-data-access/src/models/audit.js
- packages/spacecat-shared-data-access/test/unit/service/audits/index.test.js
> fix: validate scores only needed

- package-lock.json
- packages/spacecat-shared-rum-api-client/src/index.d.ts
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/create-urls.test.js
- packages/spacecat-shared-rum-api-client/test/rum-api-client.test.js
> feat: API call for getting conversion data.

- package-lock.json
- packages/spacecat-shared-rum-api-client/src/index.d.ts
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/create-urls.test.js
- packages/spacecat-shared-rum-api-client/test/rum-api-client.test.js
> feat: calculate conversion for customer domains

- package-lock.json
- packages/spacecat-shared-data-access/docs/schema.json
- packages/spacecat-shared-data-access/src/dto/key-event.js
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/index.js
- packages/spacecat-shared-data-access/src/models/key-event.js
- packages/spacecat-shared-data-access/src/service/index.js
- packages/spacecat-shared-data-access/src/service/key-events/accessPatterns.js
- packages/spacecat-shared-data-access/src/service/key-events/index.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/it/generateSampleData.js
- packages/spacecat-shared-data-access/test/unit/models/key-event.test.js
- packages/spacecat-shared-data-access/test/unit/service/index.test.js
- packages/spacecat-shared-data-access/test/unit/service/key-events/index.test.js
Data layer impl. for https://github.com/adobe/spacecat-api-service/pull/247
> feat: key events data access layer

- packages/spacecat-shared-http-utils/src/index.js
- packages/spacecat-shared-http-utils/test/index.test.js
> feat: http created method

- packages/spacecat-shared-ahrefs-client/src/index.js
- packages/spacecat-shared-ahrefs-client/test/index.test.js
> feat(ahrefs-client): get organic traffic

- package-lock.json
- packages/spacecat-shared-utils/package.json
> fix: use local dependency instead of external dependency for data-access

- packages/spacecat-shared-gpt-client/src/clients/firefall-client.js
Add log statements needed for demo
> fix: add logs

- packages/spacecat-shared-google-client/src/index.d.ts
Fix the google client interface, using the correct response types and parameters
> fix: google client interface

- packages/spacecat-shared-google-client/src/index.js
- packages/spacecat-shared-google-client/test/index.test.js
this PR introduces filtering for the organic search data requested from google.
Examples:
For the base URL `https://ust.com/en/insights`, we currently request the data for `https://www.ust.com/`, but it should be filtered to `https://www.ust.com/en/insights`.
For the base URL `https://sunstar.com`, currently all other subdomains are included, like `https://jp.sunstar.com`, however we only want `https://www.sunstar.com`
> feat: filter fetched organic search data from google by base url

- packages/spacecat-shared-google-client/src/index.js
- packages/spacecat-shared-google-client/test/index.test.js
This PR fixes an issue where the site url is verified, even when its not needed
> fix: site url verification

- package-lock.json
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/index.js
- packages/spacecat-shared-data-access/src/models/importer/import-job.js
- packages/spacecat-shared-data-access/src/models/importer/import-url.js
> feat: Add PENDING status for import URL entities

- packages/spacecat-shared-data-access/src/models/site/audit-config-type.js
- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
Added excludedURLs to opt-out from fixing broken-backlinks 
Ticket:
https://jira.corp.adobe.com/browse/SITES-22463
Corresponding PR API: https://github.com/adobe/spacecat-api-service/pull/336
> feat: opt-out broken-backlinks

- packages/spacecat-shared-data-access/src/models/site/audit-config-type.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/it/generateSampleData.js
- packages/spacecat-shared-data-access/test/unit/models/site.test.js
- packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
> feat: opt-out brokenlinks

- packages/spacecat-shared-utils/test/helpers.test.js
> fix: some more tests

- packages/spacecat-shared-data-access/src/models/site/audit-config-type.js
- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/audit-config-type.test.js
https://jira.corp.adobe.com/browse/SITES-22728 - Overwrite Broken Backlinks
> feat: overwrite broken-backlinks

- packages/spacecat-shared-data-access/src/models/audit.js
- packages/spacecat-shared-data-access/src/models/site/audit-config.js
- packages/spacecat-shared-data-access/test/unit/models/site/audit-config.test.js
- packages/spacecat-shared-utils/test/helpers.test.js
> feat(audit-configs): ess audits disabled by default

- packages/spacecat-shared-rum-api-client/test/index.test.js
- packages/spacecat-shared-utils/src/sqs.js
Fixes possible undefined errors. Blocks #181
> fix: sqs adapter records access

- packages/spacecat-shared-data-access/package.json
> feat: update the config model for sites and orgs

- packages/spacecat-shared-data-access/package.json
> feat: update to trigger release

- packages/spacecat-shared-rum-api-client/src/functions/traffic-acquisition.js
- packages/spacecat-shared-rum-api-client/test/functions.test.js
> fix: work-around for bamboos custom exp engine

- package-lock.json
- packages/spacecat-shared-rum-api-client/package.json
- packages/spacecat-shared-rum-api-client/src/common/traffic.js
- packages/spacecat-shared-rum-api-client/test/common/traffic.test.js
Based on the RUM data, this changes decreases `owned:uncategorized` from 8% to 2.17%.
> fix: improve traffic acquisition detection

- packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js
- packages/spacecat-shared-rum-api-client/src/functions/experiment.js
- packages/spacecat-shared-rum-api-client/src/functions/traffic-acquisition.js
Fixes [SITES-23730](https://jira.corp.adobe.com/browse/SITES-23730)
> feat: add support for multiple experiments on the same page

- package-lock.json
- packages/spacecat-shared-data-access/docs/schema.json
- packages/spacecat-shared-data-access/src/dto/import-job.js
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/models/importer/import-job.js
- packages/spacecat-shared-data-access/test/unit/models/importer/import-job.test.js
- packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js
[SITES-23948](https://jira.corp.adobe.com/browse/SITES-23948)
Update spacecat-shared data access models for import-job to be hashedApiKey instead of apiKey
> feat: update import job models to include hashed key

- packages/spacecat-shared-http-utils/src/index.js
[SITES-23633](https://jira.corp.adobe.com/browse/SITES-23633)
Export ScopedApiKeyHandler for spacecat-api-service.
Relevant PR: https://github.com/adobe/spacecat-api-service/pull/442
> feat: export ScopedApiKeyHandler

- package-lock.json
- packages/spacecat-shared-http-utils/src/auth/handlers/scoped-api-key.js
Add more debug logs to figure out the issue in ScopedApiKeyHandler.
Currently it doesn't print the log 
```
this.log(`Checking for API key with hash: ${hashedApiKey}`, 'debug');
```
> fix: add more debug logs

- packages/spacecat-shared-data-access/test/it/db.test.js
> test: change position of key events it tests

- .github/workflows/main.yaml
- package-lock.json
- packages/spacecat-shared-data-access/docs/schema.json
- packages/spacecat-shared-data-access/package.json
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/it/generateSampleData.js
- renovate.json5
Updating `dynamo-db-local` to latest major version to bring fixes and stability. Updates: https://github.com/chrisguttandin/dynamo-db-local/compare/v8.0.0...v9.2.0
> chore(deps): update dynamo-db-local

- packages/spacecat-shared-data-access/test/it/db.test.js
> test: update key events tests

- package-lock.json
- packages/spacecat-shared-google-client/src/index.js
- packages/spacecat-shared-google-client/test/index.test.js
This PR fixes a small bug, if the auth token was recently added, it might not be valid for SpaceCat and needs to be refreshed at all times.
> fix: authentication token refresh

- packages/spacecat-shared-data-access/test/unit/models/importer/import-url.test.js
Trigger a release for spacecat-shared.
It got missed out for the following PR: https://github.com/adobe/spacecat-shared/pull/373
> fix: add an additional space in the unit test

- packages/spacecat-shared-utils/src/log-wrapper.js
- packages/spacecat-shared-utils/test/log-wrapper.test.js
> fix: add null check for empty message in logWrapper

- packages/spacecat-shared-rum-api-client/README.md
- packages/spacecat-shared-rum-api-client/src/common/aggregateFns.js
- packages/spacecat-shared-rum-api-client/src/common/traffic.js
- packages/spacecat-shared-rum-api-client/src/functions/opportunities/high-inorganic-high-bounce-rate.js
- packages/spacecat-shared-rum-api-client/src/functions/opportunities/high-organic-low-ctr.js
- packages/spacecat-shared-rum-api-client/src/functions/opportunities/rageclick.js
- packages/spacecat-shared-rum-api-client/src/functions/traffic-acquisition.js
- packages/spacecat-shared-rum-api-client/test/common/traffic.test.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-with-traffic-source.json
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles.json
- packages/spacecat-shared-rum-api-client/test/fixtures/high-inorganic-high-bounce.json
- packages/spacecat-shared-rum-api-client/test/fixtures/high-organic-low-ctr.json
- packages/spacecat-shared-rum-api-client/test/fixtures/trafficSources.json
- packages/spacecat-shared-rum-api-client/test/functions.test.js
- This improvement will add top 5 traffic sources from referrer data in RUM and also provides the CTR. The overall page views and ctr will be available in `"vendor": "*"`
- Example opportunity data
```
{
"type": "high-organic-low-ctr",
"page": "https://www.example.com/test-it.html",
"screenshot": "",
"trackedPageKPIName": "Click Through Rate",
"trackedPageKPIValue": 0.04880226208028238,
"pageViews": 1452822,
"samples": 1452822,
"trackedKPISiteAverage": 0.2939925740425318,
"metrics": [
{
"type": "traffic",
"vendor": "*",
"value": {
"total": 1452822,
"paid": 209700,
"owned": 748122,
"earned": 495000
}
},
{
"type": "ctr",
"vendor": "*",
"value": {
"page": 0.04880226208028238
}
},
{
"type": "traffic",
"vendor": "google",
"value": {
"total": 597300,
"owned": 0,
"earned": 402200,
"paid": 195100 …
```
> fix: Improve granularity of high organic traffic audit

- packages/spacecat-shared-data-access/CHANGELOG.md
- packages/spacecat-shared-data-access/docs/schema.json
- packages/spacecat-shared-data-access/package.json
- packages/spacecat-shared-data-access/src/dto/import-job.js
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/models/importer/import-job.js
- packages/spacecat-shared-data-access/test/it/db.test.js
- packages/spacecat-shared-data-access/test/unit/models/api-key.test.js
- packages/spacecat-shared-data-access/test/unit/models/importer/import-job.test.js
- packages/spacecat-shared-data-access/test/unit/service/import-job/index.test.js
Add a unit test for imports.write_all_domains scope
> fix: Add a unit test for imports.write_all_domains scope

- packages/spacecat-shared-data-access/src/models/api-key.js
- packages/spacecat-shared-data-access/test/unit/models/api-key.test.js
https://jira.corp.adobe.com/browse/SITES-22756
Reference PR: https://github.com/adobe/spacecat-api-service/pull/511/files
> fix: Modify the scope name to imports.all_domains

- packages/spacecat-shared-data-access/src/dto/configuration.js
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/models/configuration.js
- packages/spacecat-shared-data-access/test/unit/models/configuration.test.js
> feat: added `slackRoles` access methods to configuration and model

- package-lock.json
- packages/spacecat-shared-dynamo/package.json
- packages/spacecat-shared-dynamo/src/index.js
- packages/spacecat-shared-google-client/package.json
- packages/spacecat-shared-google-client/src/index.js
- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/s3.js
- packages/spacecat-shared-utils/src/sqs.js
Adding AWS X-Ray tracing instrumentation for v3 AWS clients.
> fix: add tracing support for v3 aws clients

- package-lock.json
- packages/spacecat-shared-data-access/src/index.d.ts
- packages/spacecat-shared-data-access/src/models/importer/import-constants.js
- packages/spacecat-shared-data-access/test/unit/models/importer/import-job.test.js
Adds a new `ImportJobStatus`: `STOPPED`
- [SITES-23397](https://jira.corp.adobe.com/browse/SITES-23397)
> feat: Support cancelling / stopping a running job

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
https://jira.corp.adobe.com/browse/SITES-24889 [Auto Detect] Introduce configurable grouping patterns for CWV data
https://github.com/adobe/spacecat-api-service/pull/571
https://github.com/adobe/spacecat-shared/pull/439
https://github.com/adobe/spacecat-audit-worker/pull/462
> feat: Introduce configurable grouping patterns

- packages/spacecat-shared-data-access/src/models/configuration.js
- packages/spacecat-shared-data-access/test/unit/models/configuration.test.js
https://jira.corp.adobe.com/browse/SITES-26808
> feat: Adding getEnabledSiteIdsForHandler in Configuration

- package-lock.json
- packages/spacecat-shared-rum-api-client/package.json
> fix(deps): bump rum-distiller to 1.9.1

- packages/spacecat-shared-rum-api-client/README.md
- packages/spacecat-shared-rum-api-client/src/functions/cwv.js
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/bundles-for-url-patterns.json
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/result-for-url-patterns.json
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/result-for-urls.json
> fix(cwv): include organic pageviews in the response

- packages/spacecat-shared-rum-api-client/src/functions/cwv.js
- packages/spacecat-shared-rum-api-client/test/cwv.test.js
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/bundles-for-url-patterns.json
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/result-for-url-patterns.json
- packages/spacecat-shared-rum-api-client/test/fixtures/cwv/result-for-urls.json
https://jira.corp.adobe.com/browse/SITES-26928
> feat: Include site level metrics in the CWV response

- packages/spacecat-shared-rum-api-client/README.md
> fix(cwv): Update Core Web Vitals (CWV) in README to reflect newly added functionality.

- packages/spacecat-shared-data-access/src/service/site-candidates/accessPatterns.js
> fix(data-access): get all site candidates table name

- packages/spacecat-shared-rum-api-client/src/functions/404-internal-links.js
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/cwv.test.js
- packages/spacecat-shared-rum-api-client/test/fixtures/404-internal-links-result.json
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-404-internal-links.json
- packages/spacecat-shared-rum-api-client/test/functions.test.js
**Test cases coming soon.**
This PR introduces a 404 links handler from internal sources - same domain.
It handles `navigate` and `404` events and sums views from same source/target combos that has both of above events.
https://jira.corp.adobe.com/browse/SITES-27242
```
[
{
"id": "56ou",
"host": "rum.hlx.page",
"time": "2024-11-23T23:00:01.858Z",
"timeSlot": "2024-11-23T23:00:00.000Z",
"url": "https://www.petplace.com/a01",
"userAgent": "mobile:android:blink",
"weight": 200,
"events": [
{
"checkpoint": "navigate",
"target": "visible",
"source": "https://www.petplace.com/a01nf",
"timeDelta": 1858
},
{
"checkpoint": "navigate",
"target": "visible",
"source": "https://www.petplace.com/a01nf",
"timeDelta": 1654
},
{
"checkpoint": "404",
"target": "",
"source": …
```
> First commit for 404 internal links handler

- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/test/helpers.test.js
Move from https://github.com/adobe/spacecat-content-processor/
> feat: introduce get prompt from static files

- packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/common/rum-bundler-client.test.js
> fix(rum-api-client): log RUM Bundler requests

- packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js
- packages/spacecat-shared-rum-api-client/src/index.js
> fix(rum-api-client): extra RUM Bundler requests logging

- packages/spacecat-shared-rum-api-client/src/functions/opportunities/high-organic-low-ctr.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-with-traffic-source.json
- packages/spacecat-shared-rum-api-client/test/fixtures/high-organic-low-ctr.json
> fix(rum-api-client): only consider earned traffic in hi-org-lo-ctr

- packages/spacecat-shared-utils/src/formcalc.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/fixtures/formcalcaudit.js
- packages/spacecat-shared-utils/test/formcalc.test.js
- packages/spacecat-shared-utils/test/index.test.js
> feat: adding more opportunities utils for forms

- packages/spacecat-shared-rum-api-client/README.md
- packages/spacecat-shared-rum-api-client/src/index.d.ts
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/index.test.js
> feat(rum-api-client): admin key support

- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/helpers.test.js
- packages/spacecat-shared-utils/test/index.test.js
> fix(shared-utils): remove legacy rum domain key retrieval

- packages/spacecat-shared-data-access/src/models/site/index.d.ts
- packages/spacecat-shared-data-access/src/models/site/site.schema.js
> fix: delivery configuration

- packages/spacecat-shared-rum-api-client/src/functions/pageviews.js
- packages/spacecat-shared-rum-api-client/src/index.js
- packages/spacecat-shared-rum-api-client/test/functions.test.js
> feat(rum-api-client): pageviews query

- packages/spacecat-shared-data-access/src/models/base/base.collection.js
- packages/spacecat-shared-data-access/test/unit/models/base/base.collection.test.js
> fix(data-access): fetch all records on demand

- packages/spacecat-shared-utils/src/formcalc.js
- packages/spacecat-shared-utils/test/formcalc.test.js
> fix: adding forms constants at common place

- packages/spacecat-shared-utils/src/formcalc.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/index.test.js
> feat: changing forms api signature

- packages/spacecat-shared-utils/src/formcalc.js
- packages/spacecat-shared-utils/test/formcalc.test.js
> fix: enhance form calculations for view and submit

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-form-vitals.json
> Filter search events

- packages/spacecat-shared-utils/src/formcalc.js
- packages/spacecat-shared-utils/test/formcalc.test.js
> forms: device-wise metric collection

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-form-vitals.json
- packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
> feat: formsource wise segregation of audit result

- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Making a commit following conventional commits for create release for contentAiConfig.
> fix: add comments

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
> feat: Added cwv-daily and cwv-weekly import types

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
> fix: eliminating unnecessary data from forms vitals

- packages/spacecat-shared-data-access/src/models/site/index.d.ts
> docs(data-access): type for hlxconfig

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
> fix: changing user agent categorization for forms

- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/src/s3.js
- packages/spacecat-shared-utils/src/sqs.js
- packages/spacecat-shared-utils/src/tracing-fetch.js
- packages/spacecat-shared-utils/src/xray.js
- packages/spacecat-shared-utils/test/index.test.js
- packages/spacecat-shared-utils/test/tracing-fetch.test.js
- packages/spacecat-shared-utils/test/xray.test.js
> fix(xray): local friendly xray instrumentation

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-form-vitals.json
- packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
> feat: identify iframe forms

- packages/spacecat-shared-data-access/src/models/fix-entity/index.d.ts
- https://jira.corp.adobe.com/browse/SITES-30551
> fix: Update type definitions for FixEntity

- package-lock.json
- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
This adds the possibility to add authentication options for example
> feat: adding options to scraper sqs payload

- packages/spacecat-shared-utils/src/auth.js
https://jira.corp.adobe.com/browse/SITES-31664
> feat: add page authentication token retrieval functionality

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-form-vitals.json
- packages/spacecat-shared-rum-api-client/test/fixtures/expected-form-vitals-result.json
> feat: detect iframe forms; bug fix for duplicated iframes with #

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
> Filter Forms that submit to an endpoint containing the term search

- packages/spacecat-shared-http-utils/src/index.js
> fix: expose cookie handler

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
Small PR with one addition:
- ACCESSIBILITY as an audit type in AUDIT_TYPES
> feat: added accessibility as an audit type

- packages/spacecat-shared-data-access/src/models/site/config.js
> feat: add `organic-keywords-nonbranded` import type to site config

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
https://jira.corp.adobe.com/browse/FORMS-20089
> fix: disregarding CTAs without a valid source for low nav opportunities

- packages/spacecat-shared-rum-api-client/src/functions/form-vitals.js
- packages/spacecat-shared-rum-api-client/test/fixtures/bundles-for-form-vitals.json
> feat: filter pages under experiment

- packages/spacecat-shared-ahrefs-client/src/index.js
> Fix: ahrefs serp features field name

- packages/spacecat-shared-data-access/src/models/site/config.js
> fix: new organic keyword imports configs

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
> fix: typo issue for elmo

- packages/spacecat-shared-http-utils/src/auth/handlers/ims.js
> fix: trigger a release for non-adobe users tenant isolation

- packages/spacecat-shared-utils/src/functions.js
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/functions.test.js
- packages/spacecat-shared-utils/test/index.test.js
> feat: introduce isValidHelixPreviewUrl in context of preflight audits

- packages/spacecat-shared-utils/src/helpers.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/index.test.js
> feat: expose getStaticContent function

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Add CDN logs config for site model
> feat: add CDN logs config

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
add setter for cdn logs condfig
> fix: add setter for cdn logs condfig

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
make filter value array for cdn config
> fix: make filter value array

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
> feat: add type for filter

- packages/spacecat-shared-athena-client/src/index.js
> fix: add pagination for athena

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/src/service/index.js
- packages/spacecat-shared-data-access/src/util/index.js
- packages/spacecat-shared-data-access/src/util/logger-registry.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
Add try catch for config for sites validation
Added logger to get error logs and create alerts to notify
> fix: add try catch for config for sites validation

- packages/spacecat-shared-athena-client/src/index.js
- packages/spacecat-shared-athena-client/src/queries.js
- packages/spacecat-shared-athena-client/static/queries/traffic-analysis.sql.tpl
- packages/spacecat-shared-athena-client/test/index.test.js
> feat: add traffic queries for traffic analysis to shared location

- packages/spacecat-shared-http-utils/src/index.js
- packages/spacecat-shared-http-utils/test/index.test.js
adds gzip support to the `createResponse` utils
> feat: gzip support

- packages/spacecat-shared-scrape-client/src/clients/scrape-job-supervisor.js
- packages/spacecat-shared-scrape-client/test/index.test.js
- added url-batching before sending messages to sqs
- use baseUrl as message groupeId to ensure the order of the urls don't change
- updated unit tests
> Fix handle large url lists

- packages/spacecat-shared-rum-api-client/src/common/rum-bundler-client.js
> feat(rum-client): add log checkpoints for around every 50k bundles fetched

- packages/spacecat-shared-athena-client/src/traffic-analysis/traffic-data-base-response.js
- packages/spacecat-shared-athena-client/test/index.test.js
> fix: mapping

- packages/spacecat-shared-athena-client/src/traffic-analysis/queries.js
- packages/spacecat-shared-athena-client/src/traffic-analysis/traffic-analysis-template.js
- packages/spacecat-shared-athena-client/test/index.test.js
allow filter on traffic type before grouping
> fix: introduce filter on traffic type

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
Add hreflang as an  Audit.AUDIT_TYPES
> feat: hreflang as an audit type

- packages/spacecat-shared-data-access/src/models/site/config.js
https://jira.corp.adobe.com/browse/LLMO-19
https://jira.corp.adobe.com/browse/LLMO-36
https://jira.corp.adobe.com/browse/LLMO-185
> feat: simpler config for llmo-prompts-ahref import

- packages/spacecat-shared-utils/src/url-helpers.js
- packages/spacecat-shared-utils/test/url-helpers.test.js
> feat: return null instead of throwing error

- packages/spacecat-shared-rum-api-client/src/common/traffic.js
- packages/spacecat-shared-rum-api-client/test/common/traffic.test.js
> fix(rum-api-client): harden LLM-related classifications

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
added readability to AUDIT_TYPES. Please let me know if all makes sense or if anything else is needed! Let me know if package or package-lock needs to be updated.
> fix: add readability as audit type

- package-lock.json
- packages/spacecat-shared-data-access/package.json
- packages/spacecat-shared-data-access/src/models/site/site.model.js
Dependent on https://github.com/adobe/spacecat-shared/pull/927
> fix: use DELIVERY_TYPES from shared-utils

- package-lock.json
- packages/spacecat-shared-scrape-client/README.md
- packages/spacecat-shared-scrape-client/src/clients/scrape-client.js
- packages/spacecat-shared-scrape-client/src/clients/scrape-job-supervisor.js
- added scrape-workflow to the readme
- updated jsDoc
> docs(scrapeClient): added scrape-workflow to the readme

- package-lock.json
- packages/spacecat-shared-utils/package.json
- packages/spacecat-shared-utils/src/functions.js
- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/index.js
- packages/spacecat-shared-utils/test/functions.test.js
- packages/spacecat-shared-utils/test/index.test.js
- Install validator package for robust email validation
- Add isValidEmail function following existing naming conventions
- Add tests for valid and invalid emails
> feat: add email validation function using validator package

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
> feat: add headings audit

- packages/spacecat-shared-data-access/src/models/site/config.js
- packages/spacecat-shared-data-access/test/unit/models/site/config.test.js
> feat: add bucket config inside llmo

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
> feat: add security audit types

- packages/spacecat-shared-tier-client/src/tier-client.js
- packages/spacecat-shared-tier-client/test/tier-client.test.js
> feat: entitlement with out site and upgrade

- packages/spacecat-shared-http-utils/src/auth/handlers/ims.js
- packages/spacecat-shared-http-utils/test/auth/handlers/ims.test.js
> fix: track IMS handler usage

- packages/spacecat-shared-tier-client/src/tier-client.js
- packages/spacecat-shared-tier-client/test/tier-client.test.js
> fix: move logs to debug

- packages/spacecat-shared-html-analyzer/.releaserc.cjs
> fix: release package

- packages/spacecat-shared-data-access/src/models/audit/audit.model.js
- packages/spacecat-shared-data-access/test/unit/models/audit/audit.model.test.js
https://jira.corp.adobe.com/browse/COMOPT-1168
> feat(COMOPT-1168): add PRODUCT_METATAGS to AUDIT_TYPES and update tests

- packages/spacecat-shared-utils/src/index.d.ts
- packages/spacecat-shared-utils/src/llmo-config.js
- packages/spacecat-shared-utils/test/llmo-config.test.js
https://jira.corp.adobe.com/browse/LLMO-436
> feat: llmo config types and version
